# Generated by Django 4.2.5 on 2023-09-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_rename_title_product_name_remove_product_composition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodapp',
            new_name='application',
        ),
    ]
