# Generated by Django 4.2.5 on 2023-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_rename_prodapp_product_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BG', 'Bags'), ('BD', 'Beads'), ('CL', 'Clothes'), ('SH', 'Shoes')], max_length=10),
        ),
    ]
